[global.config]
as = 65101
router-id = "34.215.74.23"

[[neighbors]]
  [neighbors.config]
    peer-as = 65101
    neighbor-address = "52.35.78.139"
  [neighbors.ebgp-multihop.config]
    enabled = true
    multihop-ttl = 3
[[neighbors]]
  [neighbors.config]
    peer-as = 65202
    neighbor-address = "35.160.26.195"
[neighbors.ebgp-multihop.config]
    enabled = true
    multihop-ttl = 3
[[neighbors]]
  [neighbors.config]
    peer-as = 65202
    neighbor-address = "35.162.105.70"
[neighbors.ebgp-multihop.config]
    enabled = true
    multihop-ttl = 3
