[global.config]
as = 65202
router-id = "52.40.35.189"

[[neighbors]]
  [neighbors.config]
    peer-as = 65202
    neighbor-address = "52.40.35.189"
  [neighbors.ebgp-multihop.config]
    enabled = true
    multihop-ttl = 3
[[neighbors]]
  [neighbors.config]
    peer-as = 65101
    neighbor-address = "34.213.104.214"
  [neighbors.ebgp-multihop.config]
    enabled = true
    multihop-ttl = 3
[[neighbors]]
  [neighbors.config]
    peer-as = 65101
    neighbor-address = "52.12.70.45"
  [neighbors.ebgp-multihop.config]
    enabled = true
    multihop-ttl = 3
  
